name: Test The Application

on: [pull_request]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build & Run the Docker development image 
        run: docker compose up --build --detach development

      - name: Run Prettier
        run: docker compose exec backend_development npm run format:check

      - name: Run Linter
        run: docker compose exec backend_development npm run lint:check

      - name: Run tests
        run: docker compose exec backend_development npm run test

      - name: Build & Run the Docker production image 
        run: docker compose up --build --detach production