name: Test The Application

on: 
  pull_request:
    branches: [ main ]
  push:
    branches: [ dev ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker development image 
        run: export $(grep -v '^#' .env.example | xargs) && docker compose build development

      - name: Run Prettier
        run: docker run backend_development sh -c "npm run format:check"

      - name: Run Linter
        run: docker run backend_development sh -c "npm run lint:check"

      - name: Run  unite tests
        run: docker run backend_development sh -c "npm run test"

      - name: Run e2e tests
        run: docker run backend_development sh -c "npm run test:e2e"

      - name: Build & Run the Docker production image
        run: docker compose up --build --detach production